info:
  profile: dev

spring:
  datasource:
    username: aaa
    password: '{cipher}AQBTh1hHTDXRgxa01nNPZ41Hl0wgVS2x7aLBZFHOvALfLgzLyY4710HRqfnjaEu8lbKPn/yF7ajT7zMf0B6aSmDzCN69mhYQQ50nQmb94eBfwJEYtbM8Qvc94Nr3reinFvfaQg748m3QCR+IIUxAIvi+MyHvxgEIzvW3UKb+Qkp1tbX0gsNtLD77RwrGTG+mcgwoTUpLic4Zw6UmrCq+cn0fiNCtj63OOLsvFL0yy9fE3h0p3FAgKyXiyaKU9cD6UkamY+ErJrKdFZAYUSvfijNp4k9bIfa8BwYQK3VMI706+KrdYd1DJlwD0Y9bSchQG7pcqR7Q6wocWZzMyU95MyZROaUJXSbN05gCKG/MYaK+QXsU+Eg45JT8I/p0ZxEtGmw='
