info:
  profile: dev

spring:
  datasource:
    username: aaa
    password: '{cipher}AQBb9+dMUxolgJg/TbHNnRiHw0PFRg8e9K58fp37HYXwccbd4viViptbw88jhVPwn26jE20aDiU6EvsfbRAw3z4mymMSkAvYRk+pZxjxuPPP3s7aSFuMtoNnyb17/WA6+9/botI3E8PZZQ3VzHJMx7WnjHCP0WHPGEHrnHXFdIt9tSmQ1x3Jfu4kTTM3WDLF7qMJcaMH0hmrG1MOj6myovND+InF9Qal4JWi27xCSO/CZMag3YaungaQba/adM7EcPugBaFdB+LuCYrxYVnA/UIjKbdrkVhoRdY48JHinJZlzrPgaKhnRGE7YS0WB+kep5R9X/BKQCgcBYlzGXNv7tFaCZsmQkj8fl/S7G83BqxDlOOK/hgXpcukfnuQMSWUAdk='
